title: My journey to becoming the world class developer ! 🚀
author: Buari Bola Ahmed

description: > # this means to ignore newlines until "baseurl: "
 Here I post on weekly basis on how I am moving to my ultimate goal of becoming a world class developer. I try to post what I learn, my goals, achievements and wins!
# social links
twitter_username: bolah2009
github_username:  bolah2009

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-architect
